version : "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: "database"
    ports:
      - "3307:3307"
    environment:
      - DB_USER=root
      - DB_PASSWORD=jesse jesse
      - DB_ADDRESS=localhost
      - DB_PORT=3306
      - DB_NAME=banking
    networks:
      - fullstack
    volumes:
      - database_mysql:/var/lib/mysql/data


  web:
    build: .
    container_name: "rest-api"
    environment:
      DB_USER: "root"
      DB_PASSWORD:  "jesse jesse"
      DB_ADDRESS: "localhost"
      DB_PORT: "3307"
      DB_NAME: "banking"
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_mysql:

networks:
  fullstack:
    driver: bridge