version : "3.9"

services:
  mysqldb:
    image: mysql:8.0.28
    build: ./db
    platform: linux/x86_64
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=banking
    networks:
      - golang-net

  golang-practice-project:
    build: .
    ports:
      - '8082:8082'
    networks:
      - golang-net
    environment:
      DB_USER: "root"
      DB_PASSWORD: "secret"
      DB_ADDRESS: "mysqldb"
      DB_PORT: "3306"
      DB_NAME: "banking"
      SERVER_PORT: "8082"
      AUTH_SERVICE_VERIFY_PATH: "/auth/verify"
      DOCKER_AUTH_SERVICE_HOST: "host.docker.internal:8081"
    depends_on:
      - mysqldb

  golang-auth-project:
    image: 'jesserahman1/golang-auth:no-env-file'
    ports:
      - '8081:8081'
    networks:
      - golang-net
    environment:
      DB_USER: "root"
      DB_PASSWORD: "secret"
      DB_ADDRESS: "mysqldb"
      DB_PORT: "3306"
      DB_NAME: "banking"
      HMAC_SAMPLE_SECRET: "HMAC_SAMPLE_SECRET"
      SERVER_PORT: "8081"
    depends_on:
      - mysqldb

networks:
  golang-net:
    driver: bridge