version : "3.9"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=jesse jesse
      - MYSQL_DATABASE=banking
    networks:
      - fullstack

  web:
    build: .
    environment:
      DB_USER: "root"
      DB_PASSWORD:  "jesse jesse"
      DB_ADDRESS: "mysql"
      DB_PORT: "3306"
      DB_NAME: "banking"
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - fullstack


networks:
  fullstack:
    driver: bridge